# https://taskfile.dev

version: "3"

vars:
  CONTENT: "./content/posts"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  generate-images:
    cmds:
      - echo "Generating images..."
    silent: true
  generate-svgs:
    cmds:
      - |
        find . -name '*.d2' | while read -r file; do
          d2 "$file" "${file%.d2}.svg"
        done
    desc: Generate images from D2 files
    silent: true
  new-post:
    desc: Create a new blog post
    cmds:
      - ./scripts/newPost.sh {{.CONTENT}}
